env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - "prettier"
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: { "@typescript-eslint/no-explicit-any": 0,
"@typescript-eslint/no-non-null-assertion": "error" }
